controller_list:
  - name: fake_arm_group_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
  - name: fake_head_group_controller
    joints:
      - head_pan_joint
      - head_tilt_joint